### ISSUE TITLE
Recommendation: Pre-Commit

### ISSUE THREAD

**Issue by XavierBalderdash** [Oeathus/AAFDayZ#1]
You may want to look at including a pre-commit file. https://pre-commit.com/
Having the following file, as well as pre-commit, would check your files with each commit.
Once pre-commit is installed and ran for the first time, you should commit the changes it fixes, especially in your xml files in db.
```yaml
#.pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
        name: check yaml
        description: checks yaml files for parseable syntax.
        entry: check-yaml
        language: python
        types: [yaml]

    -   id: check-xml
        name: check xml
        description: checks xml files for parseable syntax.
        entry: check-xml
        language: python
        types: [xml]

    -   id: check-json
        name: check json
        description: checks json files for parseable syntax.
        entry: check-json
        language: python
        types: [json]

    -   id: end-of-file-fixer
        name: fix end of files
        description: ensures that a file is either empty, or ends with one newline.
        entry: end-of-file-fixer
        language: python
        types: [text]
        stages: [commit, push, manual]

    -   id: trailing-whitespace
        name: trim trailing whitespace
        description: trims trailing whitespace.
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
        stages: [commit, push, manual]
```
